name: internship_website
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.3+1
  html_editor_enhanced: ^2.5.1
  textfield_tags: ^2.0.2
  flutter_mobx: ^2.0.6+5
  html_parser_plus: ^0.0.1
  firebase_storage: ^11.0.14
  flutter_quill: ^6.3.2
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  shared_preferences: ^2.0.17
  filesystem_picker: ^3.1.0
  path_provider: ^2.0.12
  flutter_spinkit: ^5.1.0
  flutter_quill_extensions: ^0.1.0
  image_picker: ^0.8.6+1
  readmore: ^2.1.0
  flutter_html: ^3.0.0-alpha.6
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  flutter_image_compress: ^1.1.3
  image_cropper: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/facebook.png
    - assets/instagram.png
    - assets/linkedin.png
    - assets/twitter.png
    - assets/write.png
    - assets/views.png
    - assets/likes.png
    - assets/comments.png
    - assets/profile.jpg
    - assets/noimage.jpg
